// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrfpgDC-Z5k1C_kf6GJquPn92eR88Ge2A',
    appId: '1:977825625575:web:e297f3fcf09e1b9830f942',
    messagingSenderId: '977825625575',
    projectId: 'gradution-project2',
    authDomain: 'gradution-project2.firebaseapp.com',
    storageBucket: 'gradution-project2.appspot.com',
    measurementId: 'G-LKYWDBGQW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdhcZEf_xeurVim67L_PNXZzO1IJPRZg',
    appId: '1:977825625575:android:8243c752dea54e8930f942',
    messagingSenderId: '977825625575',
    projectId: 'gradution-project2',
    storageBucket: 'gradution-project2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbVDNgdLpgOgsK2TM114_nsHsBI-bc948',
    appId: '1:977825625575:ios:e3f6d45ce95ffbf630f942',
    messagingSenderId: '977825625575',
    projectId: 'gradution-project2',
    storageBucket: 'gradution-project2.appspot.com',
    androidClientId: '977825625575-2lq98lc2115n8jadof4689l7424d5uhp.apps.googleusercontent.com',
    iosClientId: '977825625575-i549en67b8gosril8pi8a3af1af90hen.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbVDNgdLpgOgsK2TM114_nsHsBI-bc948',
    appId: '1:977825625575:ios:32453b1cc19b5f0d30f942',
    messagingSenderId: '977825625575',
    projectId: 'gradution-project2',
    storageBucket: 'gradution-project2.appspot.com',
    androidClientId: '977825625575-2lq98lc2115n8jadof4689l7424d5uhp.apps.googleusercontent.com',
    iosClientId: '977825625575-irv4bhnmsgadnh1a52jbsssbk1ck4gh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebase.RunnerTests',
  );
}
